#YAML
start_date: 2000-01-01

# SIM config

# all estimates set to False in dynamic system
use_forecast_weight_estimates: False
use_forecast_div_mult_estimates: False
use_instrument_weight_estimates: False
use_instrument_div_mult_estimates: False
use_forecast_scale_estimates: False

# Trading rules
# all rules from rob

volatility_calculation:
  func: "sysquant.estimators.vol.mixed_vol_calc"
  days: 35
  min_periods: 10
  vol_abs_min: 0.0000000001
  slow_vol_years: 20
  proportion_of_slow_vol: 0.35
  backfill: True
#
use_attenuation:
   - 'breakout10'
   - 'breakout20'
   - 'breakout40'
   - 'breakout80'
   - 'breakout160'
   - 'breakout320'
   - 'relmomentum10'
   - 'relmomentum20'
   - 'relmomentum40'
   - 'relmomentum80'
   - 'mrinasset1000'
   - 'assettrend2'
   - 'assettrend4'
   - 'assettrend8'
   - 'assettrend16'
   - 'assettrend32'
   - 'assettrend64'
   - 'normmom2'
   - 'normmom4'
   - 'normmom8'
   - 'normmom16'
   - 'normmom32'
   - 'normmom64'
   - 'momentum4'
   - 'momentum8'
   - 'momentum16'
   - 'momentum32'
   - 'momentum64'
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
  relmomentum10:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 10
  relmomentum20:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 20
  relmomentum40:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 40
  relmomentum80:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 80
  mrinasset1000:
     function: systems.provided.rules.cs_mr.cross_sectional_mean_reversion
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 1000
  carry10:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 10
  carry30:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 30
  carry60:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 60
  carry125:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 125
  assettrend2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 2
         Lslow: 8
  assettrend4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 4
         Lslow: 16
  assettrend8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 8
         Lslow: 32
  assettrend16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 16
         Lslow: 64
  assettrend32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 32
         Lslow: 128
  assettrend64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 64
         Lslow: 256
  normmom2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 2
         Lslow: 8
  normmom4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 4
         Lslow: 16
  normmom8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 8
         Lslow: 32
  normmom16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 16
         Lslow: 64
  normmom32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 32
         Lslow: 128
  normmom64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 64
         Lslow: 256
  momentum4:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
  momentum8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
  momentum16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
  momentum32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
  momentum64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
  relcarry:
     function: systems.provided.rules.carry.relative_carry
     data:
          - "rawdata.smoothed_carry"
          - "rawdata.median_carry_for_asset_class"
  skewabs365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 365
  skewabs180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 180
  skewrv365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 365
  skewrv180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 180
  accel16:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 16
  accel32:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 32
  accel64:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 64
#
forecast_cap: 20.0

percentage_vol_target: 25.0

# initial capital 01-2025, do not change ever!
notional_trading_capital: 500000
base_currency: "EUR"

# https://qoppac.blogspot.com/2022/02/exogenous-risk-overlay-take-two.html
# default
#risk_overlay:
#  max_risk_fraction_normal_risk: 1.75
#  max_risk_fraction_stdev_risk: 4.0
#  max_risk_limit_sum_abs_risk: 4.0
#  max_risk_leverage: 20.0
#
# target 25% Rob
risk_overlay:
  max_risk_fraction_normal_risk: 1.4
  max_risk_fraction_stdev_risk: 3.6
  max_risk_limit_sum_abs_risk: 3.4
  max_risk_leverage: 13


# from static estimation: instrument_div_multiplier, instrument_weights, forecast_scalars, forecast_weights, forecast_div_multiplier

forecast_div_multiplier:
  BUTTER: 1.319351439839144
forecast_scalars:
  accel16: 5.62073084379845
  accel32: 3.552893708388073
  accel64: 2.254115789274294
  assettrend16: 12.686342280278964
  assettrend2: 38.71850531151755
  assettrend32: 7.5170050745108545
  assettrend4: 27.76473408531406
  assettrend64: 4.469268981601058
  assettrend8: 19.385108347809307
  breakout10: 0.7318165763521798
  breakout160: 0.8709596065874209
  breakout20: 0.8150769801657136
  breakout320: 0.8702642577798049
  breakout40: 0.8391930663032888
  breakout80: 0.8287367782260542
  carry10: 6.6912740294993664
  carry125: 10.36596442384527
  carry30: 7.36918543666964
  carry60: 8.44999055043144
  momentum16: 3.091703970517406
  momentum32: 2.0257065683842317
  momentum4: 7.3318487150961795
  momentum64: 1.3574789968451961
  momentum8: 4.738122512338182
  mrinasset1000: .nan
  normmom16: 12.69875330287987
  normmom2: 39.113201407365274
  normmom32: 7.536101581250042
  normmom4: 27.876229867586353
  normmom64: 4.482317100728157
  normmom8: 19.424834931421884
  relcarry: .nan
  relmomentum10: .nan
  relmomentum20: .nan
  relmomentum40: .nan
  relmomentum80: .nan
  skewabs180: 3.9836146160776744
  skewabs365: 1.8126078589441204
  skewrv180: 4.347616137477768
  skewrv365: 2.307058740057726
forecast_weights:
  BUTTER:
    accel16: 0.27815328295735026
    accel32: 0.1577603872625703
    accel64: 0.06975694825749998
    assettrend16: 0.0060915010546874655
    assettrend2: 0.04102358084572743
    assettrend32: 1.2663772203652986e-18
    assettrend4: 0.020564700462549136
    assettrend64: 1.1083191362682662e-18
    assettrend8: 0.03678641737502372
    breakout10: 0.08195408274176334
    breakout160: 4.911418138382478e-18
    breakout20: 0.08103588906144552
    breakout320: 5.074226127914916e-18
    breakout40: 0.03160627449437506
    breakout80: 0.013183007270062422
    carry10: 2.4015438023247526e-18
    carry125: 1.1635358460602271e-18
    carry30: 2.521667589108664e-20
    carry60: 9.099388302837921e-26
    momentum16: 0.006523034991741142
    momentum32: 1.0800066708110878e-18
    momentum4: 0.04110344450454979
    momentum64: 2.5824732309804233e-18
    momentum8: 0.02967262647835701
    mrinasset1000: 0.0
    normmom16: 0.006298729807662437
    normmom2: 0.04102358084572743
    normmom32: 3.263053909957265e-18
    normmom4: 0.020564700462549136
    normmom64: 2.859185492724276e-19
    normmom8: 0.0368978111263584
    relcarry: 0.0
    relmomentum10: 0.0
    relmomentum20: 0.0
    relmomentum40: 0.0
    relmomentum80: 0.0
    skewabs180: 6.926008952844491e-18
    skewabs365: 2.0182062171189318e-17
    skewrv180: 1.2305168684960938e-19
    skewrv365: 6.655689653792959e-18
instrument_div_multiplier: 1.0
instrument_weights:
  BUTTER: 1.0
