#YAML
start_date: 2000-01-01

# SIM config

# all estimates set to False in dynamic system
use_forecast_weight_estimates: False
use_forecast_div_mult_estimates: False
use_instrument_weight_estimates: False
use_instrument_div_mult_estimates: False
use_forecast_scale_estimates: False

# Trading rules
# all rules from rob

volatility_calculation:
  func: "sysquant.estimators.vol.mixed_vol_calc"
  days: 35
  min_periods: 10
  vol_abs_min: 0.0000000001
  slow_vol_years: 20
  proportion_of_slow_vol: 0.35
  backfill: True
#
use_attenuation:
   - 'breakout10'
   - 'breakout20'
   - 'breakout40'
   - 'breakout80'
   - 'breakout160'
   - 'breakout320'
   - 'relmomentum10'
   - 'relmomentum20'
   - 'relmomentum40'
   - 'relmomentum80'
   - 'mrinasset1000'
   - 'assettrend2'
   - 'assettrend4'
   - 'assettrend8'
   - 'assettrend16'
   - 'assettrend32'
   - 'assettrend64'
   - 'normmom2'
   - 'normmom4'
   - 'normmom8'
   - 'normmom16'
   - 'normmom32'
   - 'normmom64'
   - 'momentum4'
   - 'momentum8'
   - 'momentum16'
   - 'momentum32'
   - 'momentum64'
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
  relmomentum10:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 10
  relmomentum20:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 20
  relmomentum40:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 40
  relmomentum80:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 80
  mrinasset1000:
     function: systems.provided.rules.cs_mr.cross_sectional_mean_reversion
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 1000
  carry10:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 10
  carry30:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 30
  carry60:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 60
  carry125:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 125
  assettrend2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 2
         Lslow: 8
  assettrend4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 4
         Lslow: 16
  assettrend8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 8
         Lslow: 32
  assettrend16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 16
         Lslow: 64
  assettrend32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 32
         Lslow: 128
  assettrend64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 64
         Lslow: 256
  normmom2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 2
         Lslow: 8
  normmom4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 4
         Lslow: 16
  normmom8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 8
         Lslow: 32
  normmom16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 16
         Lslow: 64
  normmom32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 32
         Lslow: 128
  normmom64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 64
         Lslow: 256
  momentum4:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
  momentum8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
  momentum16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
  momentum32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
  momentum64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
  relcarry:
     function: systems.provided.rules.carry.relative_carry
     data:
          - "rawdata.smoothed_carry"
          - "rawdata.median_carry_for_asset_class"
  skewabs365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 365
  skewabs180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 180
  skewrv365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 365
  skewrv180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 180
  accel16:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 16
  accel32:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 32
  accel64:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 64
#
forecast_cap: 20.0

percentage_vol_target: 25.0

# initial capital 01-2025, do not change ever!
notional_trading_capital: 500000
base_currency: "EUR"

# https://qoppac.blogspot.com/2022/02/exogenous-risk-overlay-take-two.html
# default
#risk_overlay:
#  max_risk_fraction_normal_risk: 1.75
#  max_risk_fraction_stdev_risk: 4.0
#  max_risk_limit_sum_abs_risk: 4.0
#  max_risk_leverage: 20.0
#
# target 25% Rob
risk_overlay:
  max_risk_fraction_normal_risk: 1.4
  max_risk_fraction_stdev_risk: 3.6
  max_risk_limit_sum_abs_risk: 3.4
  max_risk_leverage: 13


# from static estimation: instrument_div_multiplier, instrument_weights, forecast_scalars, forecast_weights, forecast_div_multiplier

forecast_div_multiplier:
  MILKDRY: 1.2571245607023562
forecast_scalars:
  accel16: 4.957908149331546
  accel32: 2.8877272789102957
  accel64: 1.7006041081708942
  assettrend16: 12.86418669250461
  assettrend2: 41.181593337443196
  assettrend32: 7.334610455607578
  assettrend4: 27.884703326420247
  assettrend64: 4.071680213410267
  assettrend8: 19.197498499396346
  breakout10: 0.6506328990876876
  breakout160: 0.8327052734716763
  breakout20: 0.7183950467741596
  breakout320: 0.8022417064381937
  breakout40: 0.7645777001138172
  breakout80: 0.8401765627035979
  carry10: 7.877570709372829
  carry125: 9.51347732696724
  carry30: 8.246402683672468
  carry60: 8.623073188784383
  momentum16: 2.675989070193502
  momentum32: 1.6512330904246846
  momentum4: 6.84748212458216
  momentum64: 1.0371291340964777
  momentum8: 4.251310417911318
  mrinasset1000: .nan
  normmom16: 12.896328770213909
  normmom2: 41.75261229715539
  normmom32: 7.341408799231423
  normmom4: 28.07631559119116
  normmom64: 4.074337554276827
  normmom8: 19.250420762059388
  relcarry: .nan
  relmomentum10: .nan
  relmomentum20: .nan
  relmomentum40: .nan
  relmomentum80: .nan
  skewabs180: 2.37748858798745
  skewabs365: 1.5369937513332808
  skewrv180: 2.782342612678676
  skewrv365: 1.8798106266477796
forecast_weights:
  MILKDRY:
    accel16: 0.34836247165357925
    accel32: 0.11842055822807755
    accel64: 0.02403615328122381
    assettrend16: 0.010946094566688288
    assettrend2: 0.026477555670256996
    assettrend32: 6.313310281832706e-20
    assettrend4: 0.013205109638253446
    assettrend64: 1.6383728724855837e-20
    assettrend8: 0.025031677063868156
    breakout10: 0.052917268878590086
    breakout160: 5.699849734562955e-11
    breakout20: 0.05256726552893249
    breakout320: 3.329747237768941e-20
    breakout40: 0.08471511780726403
    breakout80: 0.0021737486517436136
    carry10: 0.028724966765712564
    carry125: 1.2413525643570831e-17
    carry30: 3.1610082336660874e-18
    carry60: 6.318058658112957e-18
    momentum16: 0.06294410462924419
    momentum32: 0.002853352716333235
    momentum4: 0.0263932894968299
    momentum64: 7.80688553356179e-20
    momentum8: 0.04442759158291458
    mrinasset1000: 0.0
    normmom16: 0.011014412349903697
    normmom2: 0.026477555670256996
    normmom32: 2.5202699789320266e-18
    normmom4: 0.013205109638253446
    normmom64: 2.4033310783973015e-22
    normmom8: 0.025106596125074862
    relcarry: 0.0
    relmomentum10: 0.0
    relmomentum20: 0.0
    relmomentum40: 0.0
    relmomentum80: 0.0
    skewabs180: 1.8900434064064883e-16
    skewabs365: 1.1656027425916794e-16
    skewrv180: 1.1190781441505534e-17
    skewrv365: 9.225540765261578e-18
instrument_div_multiplier: 1.0
instrument_weights:
  MILKDRY: 1.0
